version: "3.7"
services:
  server:
    container_name: sentiment-analysis-server
    build:
      context: ./server
    restart: always
    environment:
      - MODEL_ID=10rThD6G29uwQelsIsX_QqlYBFUZldmxB
    ports:
      - "8000:8000"
  client:
    container_name: sentiment-analysis-client
    build:
      context: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/home/node/client
      - /home/node/client/node_modules
      - /home/node/client/.next
    restart: always
    environment:
      - NEXT_PUBLIC_API_ENDPOINT=http://localhost:8000
    depends_on:
      - "server"
